# NVIDIA Driver Manager configuration

NDM_CACHE_DIR="${HOME}/.cache/nvidia-driver-manager"
NDM_LOG_DIR="/var/log/nvidia-driver-manager"

NDM_NVIDIA_UNIX_URL="https://www.nvidia.com/en-us/drivers/unix/"
NDM_DOWNLOAD_BASE_URL="https://us.download.nvidia.com/XFree86/Linux-x86_64"

NDM_KEEP_INSTALLERS="2"
NDM_DEBUG="0"
